name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.12 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm clean-install

      - name: Audit
        run: npm audit

      - name: Audit signatures
        run: npm audit signatures

      - name: Lint
        run: npm run lint

      - name: Create environment file
        run: |
          pwd
          echo "Creating production environment file..."
          echo "${{ secrets.PRODUCTION_ENVIRONMENT_FILE }}" >> src/environments/environment.ts
          ls

#      - name: Test
#        run: npm run test:ci

      - name: Build
        run: npm run build:production
