name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.12 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm clean-install

      - name: Audit
        run: npm audit

      - name: Audit signatures
        run: npm audit signatures

      - name: Lint
        run: npm run lint

      - name: Create environment file
        run: |
          echo "Creating production environment file..."
          echo "${{ secrets.PRODUCTION_ENVIRONMENT_FILE }}" >> src/environments/environment.ts

      - name: Test
        run: npm run test:ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start Storybook server
        run: npm run storybook &

      - name: Wait for Storybook to start
        run: npx wait-on http://localhost:6006

      - name: Run Storybook tests
        run: npm run test-storybook

      - name: Stop Storybook
        run: pkill -f storybook

      - name: Run Playwright tests
        run: npm run e2e:ci

      - name: Build
        run: npm run build:production
